<?php
/**
 * RetrieveCatalogResponseTest
 *
 * PHP version 8.1
 *
 * @package  kruegge82\DPIM
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post INTERNETMARKE API
 *
 * Division: Post & Parcel Germany<br /> The INTERNETMARKE is the online-postage for mail products of Deutsche Post AG.
 *
 * The version of the OpenAPI document: 1.25
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace kruegge82\DPIM\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RetrieveCatalogResponseTest Class Doc Comment
 *
 * @description Response object for the retrieved Catalogs.
 * @package     kruegge82\DPIM
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RetrieveCatalogResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RetrieveCatalogResponse"
     */
    public function testRetrieveCatalogResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "private_catalog"
     */
    public function testPropertyPrivateCatalog()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "public_catalog"
     */
    public function testPropertyPublicCatalog()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "page_formats"
     */
    public function testPropertyPageFormats()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contract_products"
     */
    public function testPropertyContractProducts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
